#include "crypto/crypto.h"
#include "crypto/encstring.h"
#include "crypto/kdf.h"
#include "crypto/securebytes.h"
#include "crypto/symmetrickey.h"
#include "model/cipher.h"

#include <QTest>

using namespace kvault;

namespace {

QByteArray hex(const QByteArray &data)
{
    return data.toHex();
}

QByteArray fromHex(const char *text)
{
    return QByteArray::fromHex(QByteArray(text));
}

SecureBytes secure(const char *text)
{
    return SecureBytes(QByteArray(text));
}

// A synthetic account generated by an independent Python implementation of the
// documented Bitwarden scheme. Decrypting these end to end proves the key
// derivation, key stretching, unwrapping and EncString handling all agree with
// a second implementation rather than merely with themselves.
constexpr const char *TestEmail = "user@example.com";
constexpr const char *TestPassword = "correct horse battery staple";
constexpr int TestIterations = 600000;
constexpr const char *TestMasterKeyHex = "55dc4a94e4881ffd792d6cb4173d7145756cd95ddc9b2310bb0fc931123c8248";
constexpr const char *TestPasswordHash = "nfEypS52oCiXbQyehOT45BcIhAJYN/5ltdzSYVXHaWg=";
constexpr const char *TestUserKeyHex = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff"
                                       "ffeeddccbbaa99887766554433221100ffeeddccbbaa99887766554433221100";
constexpr const char *TestWrappedUserKey = "2.k5Icxo5uUODfnvcW9r2Unw==|DyjpZkZX3EmGA05mewSSr2+IuRp706hixciKCTYIVtW3QgpBYrhJujf+kTXv9Lz/"
                                           "rRgg0UP/i98oQB+Pq20VrCjOUn8hBk44xP7XswEYHlE=|0fyhADJ0PkpdumfO5vhFm9JfsSfHcmOSVNQmu8CLeOQ=";
constexpr const char *TestWrappedItemKey
    = "2.+uvuUc21hxwKmE9HCnA7lA==|5lHF0HS1meHoak2J54KP7CpyvHMPZ+ID4vbkFFnkZlk72AAvpzABr3U28eKAtgsVxRXlqRa9xLuA1fQNs0Agl9l2r1HbZksg0ttyuw6cL14="
      "|Yn74gcgUeSeZ9ojiLK4yfOwMCQ9alRvNt+pMCOCN1z8=";
constexpr const char *TestNameEnc = "2.tXuWCotKWilCQwWRuHCkdQ==|hMeX4xveJG2fImVieH87qw==|Ql0gtje1yYk95MeoPU8fCvTmnw3mgj2LzZNp8DkY/Xs=";
constexpr const char *TestUsernameEnc = "2.l0NXUmlBWjSw8hW2GFQiqw==|StHhuI7T/fmitwwoifm6/A==|Eeftttk/k4b+IxrZMkVR9JPWD1sJNX+8v/6MNccW/VY=";
constexpr const char *TestLegacyType0 = "0.AAAAAAAAAAAAAAAAAAAAAA==|qpsrEAkCTU0MIt3AMia+MA==";

} // namespace

class CryptoTest : public QObject
{
    Q_OBJECT

private Q_SLOTS:
    // --- primitives -------------------------------------------------------
    void testHmacSha256();
    void testPbkdf2Vectors();
    void testArgon2idVector();
    void testHkdfExpandRfc5869();
    void testAesCbcRoundTrip();
    void testSecureBytes();

    // --- EncString --------------------------------------------------------
    void testEncStringRoundTrip();
    void testEncStringParsesKnownCiphertext();
    void testEncStringRejectsTamperedMac();
    void testEncStringLegacyType0();
    void testEncStringMalformed();
    void testCoseEncryptionIsRejectedNotMisread();
    void testPackedBuffer();

    // --- account key chain ------------------------------------------------
    void testDeriveMasterKeyPbkdf2();
    void testMasterPasswordHash();
    void testUnwrapUserKey();
    void testFullKeyChainToCipherField();

    // --- cipher model -----------------------------------------------------
    void testCipherRoundTripAllTypes();
    void testCipherPreservesItemKey();
    void testBitwardenDateParsing();
};

void CryptoTest::testHmacSha256()
{
    // RFC 4231, test case 1.
    const SecureBytes key(QByteArray(20, '\x0b'));
    const QByteArray mac = Crypto::hmacSha256(key, QByteArrayLiteral("Hi There"));
    QCOMPARE(hex(mac), QByteArray("b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"));
}

void CryptoTest::testPbkdf2Vectors()
{
    QCOMPARE(hex(Crypto::pbkdf2Sha256(secure("password"), "salt", 1, 32).toByteArray()),
             QByteArray("120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b"));
    QCOMPARE(hex(Crypto::pbkdf2Sha256(secure("password"), "salt", 4096, 32).toByteArray()),
             QByteArray("c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a"));
}

void CryptoTest::testArgon2idVector()
{
    // Matches `argon2 somesaltsomesalt -id -t 2 -m 16 -p 1 -l 32 -r`.
    const auto result = Crypto::argon2id(secure("password"), "somesaltsomesalt", 2, 65536, 1, 32);
    QVERIFY(result.has_value());
    QCOMPARE(hex(result->toByteArray()), QByteArray("fc33b78139231d34b71626bd6245c1d72efa190ad605c3d8166a72adcedfa2c2"));
}

void CryptoTest::testHkdfExpandRfc5869()
{
    // RFC 5869 appendix A.1, expand step only.
    const SecureBytes prk(fromHex("077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5"));
    const SecureBytes okm = Crypto::hkdfExpandSha256(prk, fromHex("f0f1f2f3f4f5f6f7f8f9"), 42);
    QCOMPARE(hex(okm.toByteArray()), QByteArray("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"));
}

void CryptoTest::testAesCbcRoundTrip()
{
    const SecureBytes key = SecureBytes::random(32);
    const QByteArray iv = SecureBytes::random(16).toByteArray();

    for (const QByteArray &plaintext : {QByteArray(""), QByteArray("a"), QByteArray(16, 'x'), QByteArray(1000, 'y')}) {
        const auto ciphertext = Crypto::aesCbcEncrypt(key, iv, SecureBytes(plaintext));
        QVERIFY(ciphertext.has_value());
        // PKCS#7 always adds a block, so even empty input produces output.
        QCOMPARE(ciphertext->size() % 16, 0);
        const auto decrypted = Crypto::aesCbcDecrypt(key, iv, *ciphertext);
        QVERIFY(decrypted.has_value());
        QCOMPARE(decrypted->toByteArray(), plaintext);
    }

    // Wrong key must not produce the original plaintext.
    const auto ciphertext = Crypto::aesCbcEncrypt(key, iv, SecureBytes(QByteArray(64, 'z')));
    const auto wrong = Crypto::aesCbcDecrypt(SecureBytes::random(32), iv, *ciphertext);
    if (wrong.has_value()) {
        QVERIFY(wrong->toByteArray() != QByteArray(64, 'z'));
    }
}

void CryptoTest::testSecureBytes()
{
    SecureBytes a(QByteArrayLiteral("hello world"));
    QCOMPARE(a.size(), 11);
    QCOMPARE(a.toByteArray(), QByteArrayLiteral("hello world"));
    QCOMPARE(a.mid(6).toByteArray(), QByteArrayLiteral("world"));
    QCOMPARE(a.mid(0, 5).toByteArray(), QByteArrayLiteral("hello"));
    QCOMPARE(a.mid(50).size(), 0);

    SecureBytes b(QByteArrayLiteral("hello world"));
    QVERIFY(a == b);
    QVERIFY(a != SecureBytes(QByteArrayLiteral("hello worlx")));
    QVERIFY(a != SecureBytes(QByteArrayLiteral("short")));

    a.clear();
    QVERIFY(a.isEmpty());

    // Copies must be independent.
    SecureBytes c = b;
    c.data()[0] = 'H';
    QCOMPARE(b.toByteArray(), QByteArrayLiteral("hello world"));
    QCOMPARE(c.toByteArray(), QByteArrayLiteral("Hello world"));

    QCOMPARE(SecureBytes::random(32).size(), 32);
    QVERIFY(SecureBytes::random(32) != SecureBytes::random(32));
}

void CryptoTest::testEncStringRoundTrip()
{
    const SymmetricKey key = SymmetricKey::generate();
    QVERIFY(key.isValid());
    QVERIFY(key.hasMacKey());

    const QString plaintext = QStringLiteral("hunter2 äöü \U0001F511");
    const EncString encrypted = EncString::encryptString(plaintext, key);
    QVERIFY(!encrypted.isNull());
    QCOMPARE(encrypted.type(), EncString::AesCbc256_HmacSha256_B64);

    // Serialise and reparse, as happens when talking to the server.
    const EncString reparsed = EncString::parse(encrypted.toString());
    QVERIFY(!reparsed.isNull());
    const auto decrypted = reparsed.decryptString(key);
    QVERIFY(decrypted.has_value());
    QCOMPARE(*decrypted, plaintext);

    // A different key must fail cleanly rather than return garbage.
    QVERIFY(!reparsed.decrypt(SymmetricKey::generate()).has_value());
}

void CryptoTest::testEncStringParsesKnownCiphertext()
{
    const SymmetricKey userKey(SecureBytes(fromHex(TestUserKeyHex)));
    const auto itemKey = Cipher::resolveItemKey(QString::fromLatin1(TestWrappedItemKey), userKey);
    QVERIFY(itemKey.has_value());

    QCOMPARE(EncString::parse(QString::fromLatin1(TestNameEnc)).decryptString(*itemKey).value_or(QString()), QStringLiteral("GitHub"));
    QCOMPARE(EncString::parse(QString::fromLatin1(TestUsernameEnc)).decryptString(*itemKey).value_or(QString()), QStringLiteral("octocat"));
}

void CryptoTest::testEncStringRejectsTamperedMac()
{
    const SymmetricKey key = SymmetricKey::generate();
    const EncString original = EncString::encryptString(QStringLiteral("secret"), key);
    QString encoded = original.toString();

    // Flip a bit in the ciphertext; the MAC must catch it.
    const QStringList parts = encoded.split(u'|');
    QCOMPARE(parts.size(), 3);
    QByteArray ciphertext = QByteArray::fromBase64(parts.at(1).toLatin1());
    ciphertext[0] = char(ciphertext.at(0) ^ 0x01);
    const QString tampered = parts.at(0) + u'|' + QString::fromLatin1(ciphertext.toBase64()) + u'|' + parts.at(2);
    QVERIFY(!EncString::parse(tampered).decrypt(key).has_value());

    // Truncated MAC must be rejected too.
    QByteArray mac = QByteArray::fromBase64(parts.at(2).toLatin1());
    mac.chop(1);
    const QString shortMac = parts.at(0) + u'|' + parts.at(1) + u'|' + QString::fromLatin1(mac.toBase64());
    QVERIFY(!EncString::parse(shortMac).decrypt(key).has_value());
}

void CryptoTest::testEncStringLegacyType0()
{
    const SymmetricKey userKey(SecureBytes(fromHex(TestUserKeyHex)));
    const EncString legacy = EncString::parse(QString::fromLatin1(TestLegacyType0));
    QVERIFY(!legacy.isNull());
    QCOMPARE(legacy.type(), EncString::AesCbc256_B64);
    QCOMPARE(legacy.decryptString(userKey).value_or(QString()), QStringLiteral("legacy note"));
}

void CryptoTest::testEncStringMalformed()
{
    QVERIFY(EncString::parse(QString()).isNull());
    QVERIFY(EncString::parse(QStringLiteral("nonsense")).isNull());
    QVERIFY(EncString::parse(QStringLiteral("99.aaaa|bbbb")).isNull());
    QVERIFY(EncString::parse(QStringLiteral("2.aaaa")).isNull());
    // Type 2 requires a MAC.
    QVERIFY(EncString::parse(QStringLiteral("2.AAAAAAAAAAAAAAAAAAAAAA==|qpsrEAkCTU0MIt3AMia+MA==")).isNull());
    // A short IV is not a valid AES-CBC EncString.
    QVERIFY(EncString::parse(QStringLiteral("0.AAAA|qpsrEAkCTU0MIt3AMia+MA==")).isNull());
}

void CryptoTest::testCoseEncryptionIsRejectedNotMisread()
{
    // Bitwarden's newer "v2" encryption wraps XChaCha20-Poly1305 in COSE and
    // serialises it as a single base64 blob under type 7. KVault does not
    // implement it, and the important property is that it is recognised as a
    // known-but-unsupported format rather than misparsed as AES-CBC or silently
    // treated as corrupt.
    const QString cose = QStringLiteral("7.") + QString::fromLatin1(QByteArray("not really cose, but well formed").toBase64());

    const EncString parsed = EncString::parse(cose);
    QVERIFY(!parsed.isNull());
    QCOMPARE(parsed.type(), EncString::CoseEncrypt0);
    QVERIFY(parsed.isUnsupportedFormat());
    QVERIFY(!EncString::isSupportedType(EncString::CoseEncrypt0));

    // It must never decrypt, whatever key is offered.
    QVERIFY(!parsed.decrypt(SymmetricKey::generate()).has_value());
    QVERIFY(!parsed.decryptString(SymmetricKey::generate()).has_value());

    // And it must not be mistaken for an attachment blob.
    QVERIFY(parsed.toPackedBuffer().isEmpty());
    QByteArray packedCose;
    packedCose.append(char(EncString::CoseEncrypt0));
    packedCose.append(QByteArray(64, 'x'));
    QVERIFY(EncString::fromPackedBuffer(packedCose).isNull());

    // The classic formats are of course still supported.
    QVERIFY(EncString::isSupportedType(EncString::AesCbc256_HmacSha256_B64));
    QVERIFY(EncString::isSupportedType(EncString::AesCbc256_B64));
    QVERIFY(!EncString::parse(QStringLiteral("2.aaaa|bbbb|cccc")).isUnsupportedFormat());

    // A cipher carrying such a field reports it distinctly from corruption.
    const SymmetricKey userKey = SymmetricKey::generate();
    QJsonObject json{
        {QStringLiteral("id"), QStringLiteral("c1")},
        {QStringLiteral("type"), 1},
        {QStringLiteral("name"), cose},
    };
    const auto cipher = Cipher::fromEncryptedJson(json, userKey);
    QVERIFY(cipher.has_value());
    QVERIFY(cipher->decryptionFailed);
    QVERIFY(cipher->usesUnsupportedEncryption);

    // Whereas genuinely corrupt data is not blamed on the format.
    const auto corrupt
        = Cipher::fromEncryptedJson(QJsonObject{{QStringLiteral("type"), 1}, {QStringLiteral("name"), QStringLiteral("2.garbage")}}, userKey);
    QVERIFY(corrupt.has_value());
    QVERIFY(corrupt->decryptionFailed);
    QVERIFY(!corrupt->usesUnsupportedEncryption);
}

void CryptoTest::testPackedBuffer()
{
    const SymmetricKey key = SymmetricKey::generate();
    const QByteArray payload = SecureBytes::random(300).toByteArray();
    const EncString encrypted = EncString::encrypt(SecureBytes(payload), key);

    const QByteArray packed = encrypted.toPackedBuffer();
    QCOMPARE(uint8_t(packed.at(0)), uint8_t(EncString::AesCbc256_HmacSha256_B64));

    const EncString unpacked = EncString::fromPackedBuffer(packed);
    QVERIFY(!unpacked.isNull());
    const auto decrypted = unpacked.decrypt(key);
    QVERIFY(decrypted.has_value());
    QCOMPARE(decrypted->toByteArray(), payload);

    QVERIFY(EncString::fromPackedBuffer(QByteArray()).isNull());
    QVERIFY(EncString::fromPackedBuffer(packed.left(20)).isNull());
}

void CryptoTest::testDeriveMasterKeyPbkdf2()
{
    KdfConfig kdf;
    kdf.type = KdfType::Pbkdf2Sha256;
    kdf.iterations = TestIterations;

    const auto masterKey = AccountCrypto::deriveMasterKey(QString::fromLatin1(TestEmail), secure(TestPassword), kdf);
    QVERIFY(masterKey.has_value());
    QCOMPARE(hex(masterKey->toByteArray()), QByteArray(TestMasterKeyHex));

    // The email is normalised before use as a salt.
    const auto messyEmail = AccountCrypto::deriveMasterKey(QStringLiteral("  User@Example.COM  "), secure(TestPassword), kdf);
    QVERIFY(messyEmail.has_value());
    QCOMPARE(hex(messyEmail->toByteArray()), QByteArray(TestMasterKeyHex));
}

void CryptoTest::testMasterPasswordHash()
{
    const SecureBytes masterKey(fromHex(TestMasterKeyHex));
    const QString hash = AccountCrypto::hashMasterPassword(masterKey, secure(TestPassword), AccountCrypto::HashPurpose::ServerAuthorization);
    QCOMPARE(hash, QString::fromLatin1(TestPasswordHash));

    // The local-authorisation hash uses a different iteration count, so it must differ.
    const QString localHash = AccountCrypto::hashMasterPassword(masterKey, secure(TestPassword), AccountCrypto::HashPurpose::LocalAuthorization);
    QVERIFY(!localHash.isEmpty());
    QVERIFY(localHash != hash);
}

void CryptoTest::testUnwrapUserKey()
{
    KdfConfig kdf;
    kdf.iterations = TestIterations;
    const auto masterKey = AccountCrypto::deriveMasterKey(QString::fromLatin1(TestEmail), secure(TestPassword), kdf);
    QVERIFY(masterKey.has_value());

    const SymmetricKey stretched = SymmetricKey::stretch(*masterKey);
    QVERIFY(stretched.isValid());
    QVERIFY(stretched.hasMacKey());

    const auto userKeyMaterial = EncString::parse(QString::fromLatin1(TestWrappedUserKey)).decrypt(stretched);
    QVERIFY(userKeyMaterial.has_value());
    QCOMPARE(hex(userKeyMaterial->toByteArray()), QByteArray(TestUserKeyHex));

    // The wrong password must fail the MAC check, not silently yield a bad key.
    const auto wrongMaster = AccountCrypto::deriveMasterKey(QString::fromLatin1(TestEmail), secure("wrong password"), kdf);
    QVERIFY(!EncString::parse(QString::fromLatin1(TestWrappedUserKey)).decrypt(SymmetricKey::stretch(*wrongMaster)).has_value());
}

void CryptoTest::testFullKeyChainToCipherField()
{
    // password -> master key -> stretched key -> user key -> item key -> field
    KdfConfig kdf;
    kdf.iterations = TestIterations;
    const auto masterKey = AccountCrypto::deriveMasterKey(QString::fromLatin1(TestEmail), secure(TestPassword), kdf);
    const SymmetricKey stretched = SymmetricKey::stretch(*masterKey);
    const auto userKeyMaterial = EncString::parse(QString::fromLatin1(TestWrappedUserKey)).decrypt(stretched);
    QVERIFY(userKeyMaterial.has_value());
    const SymmetricKey userKey(*userKeyMaterial);

    const auto itemKey = Cipher::resolveItemKey(QString::fromLatin1(TestWrappedItemKey), userKey);
    QVERIFY(itemKey.has_value());
    QCOMPARE(EncString::parse(QString::fromLatin1(TestNameEnc)).decryptString(*itemKey).value_or(QString()), QStringLiteral("GitHub"));
}

void CryptoTest::testCipherRoundTripAllTypes()
{
    const SymmetricKey userKey = SymmetricKey::generate();

    Cipher login;
    login.type = CipherType::Login;
    login.name = QStringLiteral("GitHub-roundtrip-marker-A1");
    login.notes = QStringLiteral("line one\nline two");
    login.username = QStringLiteral("octocat");
    login.password = QStringLiteral("s3cr3t!");
    login.totp = QStringLiteral("JBSWY3DPEHPK3PXP");
    login.favorite = true;
    login.uris = {{QStringLiteral("https://github.com"), int(UriMatchType::Domain)}, {QStringLiteral("https://gist.github.com"), -1}};
    login.fields = {{QStringLiteral("recovery"), QStringLiteral("abc123"), int(FieldType::Hidden), -1}};
    login.passwordHistory = {{QStringLiteral("oldpass"), QDateTime::currentDateTimeUtc()}};

    Cipher note;
    note.type = CipherType::SecureNote;
    note.name = QStringLiteral("Wifi-roundtrip-marker-B2");
    note.notes = QStringLiteral("SSID: home\nPSK: letmein");

    Cipher card;
    card.type = CipherType::Card;
    card.name = QStringLiteral("Visa-roundtrip-marker-C3");
    card.cardholderName = QStringLiteral("Tim Palpant");
    card.cardBrand = QStringLiteral("Visa");
    card.cardNumber = QStringLiteral("4111111111111111");
    card.cardExpMonth = QStringLiteral("12");
    card.cardExpYear = QStringLiteral("2030");
    card.cardCode = QStringLiteral("123");

    Cipher identity;
    identity.type = CipherType::Identity;
    identity.name = QStringLiteral("Identity-roundtrip-marker-D4");
    identity.firstName = QStringLiteral("Tim");
    identity.lastName = QStringLiteral("Palpant");
    identity.email = QStringLiteral("tim@example.com");
    identity.ssn = QStringLiteral("000-00-0000");
    identity.country = QStringLiteral("US");

    Cipher sshKey;
    sshKey.type = CipherType::SshKey;
    sshKey.name = QStringLiteral("SSH-roundtrip-marker-E5");
    sshKey.sshPrivateKey = QStringLiteral("-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----");
    sshKey.sshPublicKey = QStringLiteral("ssh-ed25519 AAAA");
    sshKey.sshFingerprint = QStringLiteral("SHA256:abcdef");

    for (const Cipher &original : {login, note, card, identity, sshKey}) {
        const QJsonObject encrypted = original.toEncryptedJson(userKey);
        QVERIFY2(!encrypted.isEmpty(), qPrintable(original.name));

        // Nothing recognisable may survive into the request body. The names are
        // long and distinctive on purpose: a short string would turn up inside
        // random base64 by chance and make this check flaky rather than strict.
        const QByteArray serialised = QJsonDocument(encrypted).toJson();
        QVERIFY2(!serialised.contains(original.name.toUtf8()), qPrintable(original.name));
        if (!original.notes.isEmpty()) {
            QVERIFY(!serialised.contains(original.notes.toUtf8()));
        }

        const auto decrypted = Cipher::fromEncryptedJson(encrypted, userKey);
        QVERIFY(decrypted.has_value());
        QVERIFY(!decrypted->decryptionFailed);

        QCOMPARE(decrypted->type, original.type);
        QCOMPARE(decrypted->name, original.name);
        QCOMPARE(decrypted->notes, original.notes);
        QCOMPARE(decrypted->favorite, original.favorite);
        QCOMPARE(decrypted->username, original.username);
        QCOMPARE(decrypted->password, original.password);
        QCOMPARE(decrypted->totp, original.totp);
        QCOMPARE(decrypted->cardNumber, original.cardNumber);
        QCOMPARE(decrypted->cardCode, original.cardCode);
        QCOMPARE(decrypted->firstName, original.firstName);
        QCOMPARE(decrypted->ssn, original.ssn);
        QCOMPARE(decrypted->sshPrivateKey, original.sshPrivateKey);
        QCOMPARE(decrypted->sshFingerprint, original.sshFingerprint);
        QCOMPARE(decrypted->uris.size(), original.uris.size());
        QCOMPARE(decrypted->fields.size(), original.fields.size());
        QCOMPARE(decrypted->passwordHistory.size(), original.passwordHistory.size());
    }

    // URI match types survive the round trip, including the "default" sentinel.
    const auto decryptedLogin = Cipher::fromEncryptedJson(login.toEncryptedJson(userKey), userKey);
    QCOMPARE(decryptedLogin->uris.at(0).uri, QStringLiteral("https://github.com"));
    QCOMPARE(decryptedLogin->uris.at(0).match, int(UriMatchType::Domain));
    QCOMPARE(decryptedLogin->uris.at(1).match, int(UriMatchType::Default));
    QCOMPARE(decryptedLogin->fields.at(0).name, QStringLiteral("recovery"));
    QCOMPARE(decryptedLogin->fields.at(0).value, QStringLiteral("abc123"));
    QCOMPARE(decryptedLogin->fields.at(0).type, int(FieldType::Hidden));
}

void CryptoTest::testCipherPreservesItemKey()
{
    const SymmetricKey userKey = SymmetricKey::generate();
    const SymmetricKey itemKey = SymmetricKey::generate();
    const QString wrapped = EncString::encrypt(itemKey.full(), userKey).toString();

    Cipher cipher;
    cipher.type = CipherType::Login;
    cipher.name = QStringLiteral("With item key");
    cipher.password = QStringLiteral("pw");
    cipher.wrappedItemKey = wrapped;

    const QJsonObject encrypted = cipher.toEncryptedJson(userKey);
    QCOMPARE(encrypted.value(QStringLiteral("key")).toString(), wrapped);

    // Fields must be encrypted under the item key, not the user key.
    const EncString nameEnc = EncString::parse(encrypted.value(QStringLiteral("name")).toString());
    QVERIFY(!nameEnc.decrypt(userKey).has_value());
    QCOMPARE(nameEnc.decryptString(itemKey).value_or(QString()), QStringLiteral("With item key"));

    const auto decrypted = Cipher::fromEncryptedJson(encrypted, userKey);
    QVERIFY(decrypted.has_value());
    QCOMPARE(decrypted->name, QStringLiteral("With item key"));
    QCOMPARE(decrypted->wrappedItemKey, wrapped);
}

void CryptoTest::testBitwardenDateParsing()
{
    // The server sends seven fractional digits, which Qt rejects on its own.
    const QDateTime parsed = parseBitwardenDate(QStringLiteral("2024-05-01T12:34:56.7890000Z"));
    QVERIFY(parsed.isValid());
    QCOMPARE(parsed.toUTC().toString(Qt::ISODate), QStringLiteral("2024-05-01T12:34:56Z"));
    QCOMPARE(parsed.toUTC().time().msec(), 789);

    QVERIFY(parseBitwardenDate(QStringLiteral("2024-05-01T12:34:56Z")).isValid());
    QVERIFY(parseBitwardenDate(QStringLiteral("2024-05-01T12:34:56.123Z")).isValid());
    QVERIFY(!parseBitwardenDate(QString()).isValid());
    QVERIFY(!parseBitwardenDate(QStringLiteral("not a date")).isValid());

    // A timestamp with no zone designator is UTC, not local time.
    const QDateTime naive = parseBitwardenDate(QStringLiteral("2024-05-01T12:34:56"));
    QVERIFY(naive.isValid());
    QCOMPARE(naive, parseBitwardenDate(QStringLiteral("2024-05-01T12:34:56Z")));

    QCOMPARE(formatBitwardenDate(parsed), QStringLiteral("2024-05-01T12:34:56.789Z"));
    QVERIFY(formatBitwardenDate(QDateTime()).isEmpty());
}

QTEST_GUILESS_MAIN(CryptoTest)
#include "cryptotest.moc"
